title: Mark of DAO
author: Dmitry Baimuratov 
# email: example@gmail.com
url: https://markofdao.com
description: Devs Code. I Write.
favicon: "./favicon.ico"
show_excerpts: false
permalink: /:categories/:title
google_analytics: UA-135506355-5
  
moving:
  avatar_url: "/assets/images/profile.png"
  about_you: Devs Code. I write.
  date_format: "%b %d"
  back_to: "Home"

  social_links:
    twitter: dmitrydao 
    github: dmitrydao
    rss: RSS 

# production github-pages
remote_theme: huangyz0918/moving

# local testing
# theme: moving

plugins:
  - jekyll-feed
  - jekyll-seo-tag
